### ISSUE TITLE
Problems with Require JS in Play 2.3.8

### ISSUE THREAD

**Issue by webmans** [webjars/bpmn-js#1]
Using requireJS, the library bpmn-js cannot be loaded as expected. The script fails with the following error shown in the JS console of the browser: Uncaught Error: Script error for: bpmn-viewer

Same for bpmn-js or bpmn-modeler

The last line of the requirejs.config commands shows: requirejs.config({"paths":{}})

Adding the following two lines resolves the problem for bpmn-viewer:
requirejs.config({"paths":{"sax":["/webjars/sax/0.6.0/lib/sax","sax"]}})
requirejs.config({"paths":{"bpmn-viewer":["/webjars/bpmn-js/0.8.0/bpmn-viewer","bpmn-viewer"]},"shim":{"bpmn-js":["jquery","jquery-mousewheel","lodash","sax", "snap-svg"]}})

**Comment by jamesward** [comment]
This fix will be released as `0.8.0-1`.
